server:
  port: 9001
spring:
  webflux:
    base-path: /api
  r2dbc:
    url: r2dbcs:mysql://192.168.30.232:3306/mydb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
security:
#  auth-server: http://192.168.10.11:3002
  auth-server: http://192.168.100.104:9013